In [1]:
import polars as pl
import polars_baseline as pb

In [2]:
df = pl.read_csv('./example_phonebook_data.csv')

In [3]:
pb.count_by_email_provider(df=df)

shape: (2, 2)
┌─────────────────────┬───────┐
│ email_provider      ┆ count │
│ ---                 ┆ ---   │
│ str                 ┆ u32   │
╞═════════════════════╪═══════╡
│ otherdummyemail.com ┆ 25    │
│ dummyemail.com      ┆ 25    │
└─────────────────────┴───────┘

In [4]:
pb.count_by_state(df=df)

shape: (4, 2)
┌────────────┬───────┐
│ state      ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
│ Florida    ┆ 12    │
│ New York   ┆ 12    │
│ California ┆ 13    │
│ Texas      ┆ 13    │
└────────────┴───────┘

In [5]:
df

shape: (50, 6)
┌────────────┬───────────┬──────────────┬────────────┬─────────┬─────────────────────────────────┐
│ first_name ┆ last_name ┆ phone_number ┆ state      ┆ country ┆ email                           │
│ ---        ┆ ---       ┆ ---          ┆ ---        ┆ ---     ┆ ---                             │
│ str        ┆ str       ┆ str          ┆ str        ┆ str     ┆ str                             │
╞════════════╪═══════════╪══════════════╪════════════╪═════════╪═════════════════════════════════╡
│ John       ┆ Smith     ┆ 555-0101     ┆ California ┆ USA     ┆ john.smith@dummyemail.com       │
│ Emma       ┆ Johnson   ┆ 555-0102     ┆ Texas      ┆ USA     ┆ emma.johnson@dummyemail.com     │
│ Michael    ┆ Williams  ┆ 555-0103     ┆ New York   ┆ USA     ┆ michael.williams@dummyemail.co… │
│ Sarah      ┆ Brown     ┆ 555-0104     ┆ Florida    ┆ USA     ┆ sarah.brown@dummyemail.com      │
│ John       ┆ Jones     ┆ 555-0105     ┆ California ┆ USA     ┆ john.jones@dummyemail.com       │
│ …          ┆ …         ┆ …            ┆ …          ┆ …       ┆ …                               │
│ Emma       ┆ Rivera    ┆ 555-0146     ┆ Texas      ┆ USA     ┆ emma.rivera@otherdummyemail.co… │
│ Michael    ┆ Campbell  ┆ 555-0147     ┆ New York   ┆ USA     ┆ michael.campbell@otherdummyema… │
│ Sarah      ┆ Mitchell  ┆ 555-0148     ┆ Florida    ┆ USA     ┆ sarah.mitchell@otherdummyemail… │
│ John       ┆ Carter    ┆ 555-0149     ┆ California ┆ USA     ┆ john.carter@otherdummyemail.co… │
│ Emma       ┆ Roberts   ┆ 555-0150     ┆ Texas      ┆ USA     ┆ emma.roberts@otherdummyemail.c… │
└────────────┴───────────┴──────────────┴────────────┴─────────┴─────────────────────────────────┘

In [15]:
df.with_row_index()

shape: (50, 7)
┌───────┬────────────┬───────────┬──────────────┬────────────┬─────────┬───────────────────────────┐
│ index ┆ first_name ┆ last_name ┆ phone_number ┆ state      ┆ country ┆ email                     │
│ ---   ┆ ---        ┆ ---       ┆ ---          ┆ ---        ┆ ---     ┆ ---                       │
│ u32   ┆ str        ┆ str       ┆ str          ┆ str        ┆ str     ┆ str                       │
╞═══════╪════════════╪═══════════╪══════════════╪════════════╪═════════╪═══════════════════════════╡
│ 0     ┆ John       ┆ Smith     ┆ 555-0101     ┆ California ┆ USA     ┆ john.smith@dummyemail.com │
│ 1     ┆ Emma       ┆ Johnson   ┆ 555-0102     ┆ Texas      ┆ USA     ┆ emma.johnson@dummyemail.c │
│       ┆            ┆           ┆              ┆            ┆         ┆ om                        │
│ 2     ┆ Michael    ┆ Williams  ┆ 555-0103     ┆ New York   ┆ USA     ┆ michael.williams@dummyema │
│       ┆            ┆           ┆              ┆            ┆         ┆ il.co…                    │
│ 3     ┆ Sarah      ┆ Brown     ┆ 555-0104     ┆ Florida    ┆ USA     ┆ sarah.brown@dummyemail.co │
│       ┆            ┆           ┆              ┆            ┆         ┆ m                         │
│ 4     ┆ John       ┆ Jones     ┆ 555-0105     ┆ California ┆ USA     ┆ john.jones@dummyemail.com │
│ …     ┆ …          ┆ …         ┆ …            ┆ …          ┆ …       ┆ …                         │
│ 45    ┆ Emma       ┆ Rivera    ┆ 555-0146     ┆ Texas      ┆ USA     ┆ emma.rivera@otherdummyema │
│       ┆            ┆           ┆              ┆            ┆         ┆ il.co…                    │
│ 46    ┆ Michael    ┆ Campbell  ┆ 555-0147     ┆ New York   ┆ USA     ┆ michael.campbell@otherdum │
│       ┆            ┆           ┆              ┆            ┆         ┆ myema…                    │
│ 47    ┆ Sarah      ┆ Mitchell  ┆ 555-0148     ┆ Florida    ┆ USA     ┆ sarah.mitchell@otherdummy │
│       ┆            ┆           ┆              ┆            ┆         ┆ email…                    │
│ 48    ┆ John       ┆ Carter    ┆ 555-0149     ┆ California ┆ USA     ┆ john.carter@otherdummyema │
│       ┆            ┆           ┆              ┆            ┆         ┆ il.co…                    │
│ 49    ┆ Emma       ┆ Roberts   ┆ 555-0150     ┆ Texas      ┆ USA     ┆ emma.roberts@otherdummyem │
│       ┆            ┆           ┆              ┆            ┆         ┆ ail.c…                    │
└───────┴────────────┴───────────┴──────────────┴────────────┴─────────┴───────────────────────────┘